server:
  port: 8082

spring:
  application:
    name: scoring-engine-service

logging:
  level:
    com.walmart.ecocart: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics 