server:
  port: 8081

spring:
  application:
    name: product-metadata-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecocart_metadata
    username: ecocart_user
    password: ecocart123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

logging:
  level:
    com.walmart.ecocart: DEBUG
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics 